.github/dependabot.yml
Adds docker config, following this example: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#example-dependabotyml-file
Indenting the list should make no functional difference, but is what my editor seems to prefer for YAML, and I see it more often indented :shrug:
No story
- You should have looked at the diff against main and ensured …
=> Get dependabot to update the Dockerfile base image

app/models/assessment.rb, app/services/calculators/housing_costs_calculator.rb, app/services/calculators/monthly_equivalent_calculator.rb, app/services/calculators/monthly_income_converter.rb, app/services/calculators/state_benefits_calculator.rb, app/services/collators/childcare_collator.rb, app/services/collators/gross_income_collator.rb, app/services/collators/legal_aid_collator.rb, app/services/collators/maintenance_collator.rb, app/services/collators/outgoings_collator.rb, db/migrate/20230414114501_drop_assessment_errors.rb, db/schema.rb, spec/services/calculators/monthly_income_converter_spec.rb, spec/services/collators/childcare_collator_spec.rb, spec/services/cull_stale_assessments_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LEP/boards/1143?modal=detail&selectedIssue=LEP-91)
Describe what you did and why.
1. Created a migration to remove the assessment_errors table
2. Removed assessment_errors from code
3. Removed assessment_errors from the cull stale assessments service 
4. Updated tests 
- You should have looked at the diff against main and ensured that …
=> Lep 91 remove unused assessment errors table

Gemfile, Gemfile.lock
dependabot recently updated the pg gem to 1.5.x, however the rails adapter uses a method which is deprecated in this version. 
Pin it back to pre-1.5 until rails gets around to fixing it - lots of warning messages when running tests otherwise
=> Pin pg gem to < 1.5 due to rails incompatibility

app/services/calculators/employment_income_calculator.rb, app/services/remark_generators/frequency_checker.rb, app/services/remark_generators/orchestrator.rb, spec/requests/employments_controller_spec.rb, spec/requests/v6/assessments_controller_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
[LEP-134](https://dsdmoj.atlassian.net/browse/LEP-134)
- Allow empty payments, in the API ‘employment_income’ section request
- Make it work for V5 and V6 API
[LEP-134]: https://dsdmoj.atlassian.net/browse/LEP-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-134  Allow employment with no payments

spec/requests/properties_controller_spec.rb, spec/requests/swagger_docs/v5/full_assessment_spec.rb, spec/requests/swagger_docs/v5/properties_spec.rb, spec/requests/v6/assessments_controller_spec.rb, swagger/v5/swagger.yaml
[LEP-10](https://dsdmoj.atlassian.net/browse/LEP-10)
Current code is working without supplying `properties > main_home` parameter. Update API docs to mark `main_home` as optional parameter 
[LEP-10]: https://dsdmoj.atlassian.net/browse/LEP-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-10 mark main-home as optional request parameter

app/services/creators/eligibilities_creator.rb, spec/factories/assessment_factory.rb, spec/factories/dependant_factory.rb, spec/services/creators/eligibilities_creator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-155
When merging LEP-86, we forgot to notice that assessment.dependants is not the same as Dependant.where(assessment: assessment), as that includes partner dependants too. 
This means that an accidental defect was introduced around the threshold uplift for 4 children - when client (and partner combined) have >4 children, then the gross_income threshold should be raised by a multiplier * (children - 4)
=> LEP-155 bugfix: assessment.dependants is only client dependants

.github/dependabot.yml
Reduce frequency of dependabot updates
Dependabot is updating things every day which is distracting. 
Our sister project CCQ has this parameter set to weekly, which feels like a better tradeoff.
Note that this setting does not include security updates, which are triggered immediately
=> Dependabot is producing updates every day which is too often

app/lib/employment_income_subtotals.rb, app/services/calculators/employment_income_calculator.rb, app/services/calculators/multiple_employments_calculator.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/decorators/v5/disposable_income_result_decorator_spec.rb
[LEP-131](https://dsdmoj.atlassian.net/browse/LEP-131)
For `EmploymentIncomeSubtotals` calculate employment deductions from existing parameters instead of force-fed it
[LEP-131]: https://dsdmoj.atlassian.net/browse/LEP-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-131 Calculate employment_income_deductions

app/lib/calculation_output.rb, app/lib/gross_income_subtotals.rb, app/lib/person_gross_income_subtotals.rb, app/models/employment.rb, app/services/calculators/employment_income_calculator.rb, app/services/collators/gross_income_collator.rb, app/services/workflows/main_workflow.rb, app/services/workflows/non_passported_workflow.rb, spec/factories/gross_income_summary_factory.rb, spec/services/calculators/employment_income_calculator_spec.rb, spec/services/collators/gross_income_collator_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-137
Change calculation pipeline so that employment model no longer flows through it. This will allow a self-employment record of a similar shape to be passed
=> LEP-137 - refactor employment code

app/models/employment_payment.rb, app/services/creators/employments_creator.rb, spec/models/employment_payment_spec.rb, spec/requests/employments_controller_spec.rb, spec/requests/v6/assessments_controller_spec.rb, spec/services/creators/employments_creator_spec.rb, spec/swagger_helper.rb, swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-157
Allow negative gross income on an employment. CFE Classic had a quirk where it allowed through negative gross values if they were submitted as numbers rather than strings. This loosens the validation to allow negative numbers in this field
=> LEP-157 allow negative gross (and by implication net) employment income

.circleci/config.yml
End2end test dependencies were broken for main. This makes e2e depend on push, and the deployments depend on e2e (rather than push directly) which then depends on all the other steps
End2end tests had broken dependencies when executed on main branch. Also deployments were not dependant on end2end tests succeeding
=> Fix broken dependencies on main branch e2e tests

app/controllers/application_controller.rb, app/models/assessment.rb, app/models/request_log.rb, app/services/decorators/v6/assessment_decorator.rb, db/migrate/20230525075629_reshape_request_log.rb, db/schema.rb, spec/requests/v6/assessments_controller_spec.rb, spec/services/cull_stale_assessments_service_spec.rb, spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-146
Log v6 API requests as JSON
Once the v5 controllers have been deleted, the logging code will no longer execute. This updates it, adds a date stamp and de-couples it from the assessment database object so that it can have a separate lifecycle - especially as the long-term vision is for assessments not to be stored at all
=> Lep 146 log json v6

spec/requests/swagger_docs/v6/full_assessment_spec.rb, spec/requests/v6/assessments_controller_spec.rb, spec/spec_helper.rb, spec/swagger_helper.rb, swagger/v6/swagger.yaml
[LEP-98](https://dsdmoj.atlassian.net/browse/LEP-98)
We need to mark following fields as optional/mandatory based on their usage in calculations
- applicants.employed (optional)
- applicant.has_partner_opponent (optional)
- partner.employed (mandatory)
[LEP-98]: https://dsdmoj.atlassian.net/browse/LEP-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-98 Mark applicant and partner fields optional

spec/factories/applicant_factory.rb, spec/factories/partner_factory.rb
The applicant and partner factories make pensioners based on todays date rather than the assessment date - which means that a couple of tests broke on 8th June 2023. This makes the factories more robust, but does not fix the issue - however it defers it until 2032 which is good enough for now
=> Fix applicant and partner factories so they are less time-sensitive

app/lib/person_capital_subtotals.rb, app/services/assessors/capital_item_assessor.rb, app/services/assessors/liquid_capital_assessor.rb, app/services/assessors/non_liquid_capital_assessor.rb, app/services/collators/capital_collator.rb, spec/services/assessors/liquid_capital_assessor_spec.rb, spec/services/assessors/non_liquid_capital_assessor_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-207
To improve LEP-207, move the disputed/non-disputed vehicle split **inside** the PersonCapitalSubtotals class, so that the (now) multiple consumers of PersonCapitalSubtotals don't have to do the split themselves
=> LEP-207 PersonCapitalSubtotals refactor

infrastructure/uat/ingress-dashboard.yaml, infrastructure/uat/pods-dashboard.yaml
CCQ did these fixes, and I've directly copied them:
* EL-587/EL-886 fix colours
* EL-589 fix y-axis on rate() panels
When applied they will appear on our Grafana dashboards
* [CFE-Civil ingress](https://grafana.live.cloud-platform.service.justice.gov.uk/d/JC1OFKVbXxSY/cfe-civil-ingress?orgId=1)
* [CFE-Civil pods](https://grafana.live.cloud-platform.service.justice.gov.uk/d/0199b217f65980e0622ba969d1ed1549/cfe-civil-pods?orgId=1)
- The PR description should say what you changed and why, with …
=> Grafana dashboard fixes copied from CCQ

infrastructure/uat/ingress-dashboard.yaml, infrastructure/uat/pods-dashboard.yaml
[LEP-213](https://dsdmoj.atlassian.net/browse/LEP-213)
- Add 'cfe-crime-dev' in list of namespaces in Grafana dashboards
- Rename title "CFE Civil / Ingress" to "CFE / Ingress"
- Rename title "CFE Civil / pods" to "CFE / pods"
[LEP-213]: https://dsdmoj.atlassian.net/browse/LEP-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-213 add support for cfe-crime-dev

infrastructure/uat/pods-dashboard.yaml
Fixes this issue showing on the [Pods dashboard](https://grafana.live.cloud-platform.service.justice.gov.uk/d/0199b217f65980e0622ba969d1ed1549/cfe-pods?orgId=1&var-namespace=cfe-crime-dev&inspect=14&inspectTab=error):
No story
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the …
=> Fix bracket in Grafana dashboard

app/models/dependant.rb, app/services/calculators/childcare_eligibility_calculator.rb, app/services/creators/gross_income_eligibility_creator.rb, spec/models/dependant_spec.rb, spec/services/calculators/childcare_eligibility_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-145
Renamed #becomes_adult_on to 'becomes_16_on' to better reflect where this is being used (in childcare eligibility, where 16 is considered the threshold for not needing childcare) - nothing about being an 'adult' per se. 
Also removed state from 2 calculations to help move code about later and reduce line count
=> LEP-145 convert relationship: child_relative to DOB check

.circleci/config.yml
[LEP-216](https://dsdmoj.atlassian.net/browse/LEP-216)
**Main Branch**
When parameter `approval_required` is set to true, the deployment job requires approval before the workflow can continue running.
**Default:** `approval_required:true`
[LEP-216]: https://dsdmoj.atlassian.net/browse/LEP-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-216 deployment is done on automatic schedule

app/lib/person_wrapper.rb, app/services/calculators/childcare_eligibility_calculator.rb, app/services/workflows/non_passported_workflow.rb, features/employment/statutory_pay.feature, features/support/response_support_methods.rb, spec/services/calculators/childcare_eligibility_calculator_spec.rb, spec/services/collators/outgoings_collator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/LEP-272)
The childcare eligibility calculator was considering only if the applicants were employed when deciding if they were eligible for childcare costs. This was missing the nuance that if either of them is technically employed but receiving only statutory sick/maternity pay, they are not eligible for childcare costs. This PR adds that check.
- You …
=> LEP-282: Statutory childcare bug

docs/pull_request_template.md
(No Jira ticket - agreed to do this in Retro)
Added to the checklist updating the Changelog.
"Front-loaded" the checklist wording, making it easier to scan quickly
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.
=> Add changelog to pull_request_template.md

Gemfile.lock
This reverts commit f62eb19828cd042a77a8f6dc5266e5c41c416a27.
=> Revert "Bump rswag-api from 2.9.0 to 2.10.1 (#225)"

README.md
Threshold config files are NOT deprecated - only the USE_TEST_THRESHOLD_DATA functionality is. Made that clearer.
And fix a typo
No Jira ticket
---
=> Move the deprecation warning about USE_TEST_THRESHOLD_DATA

Gemfile, Gemfile.lock, config/environments/production.rb
https://dsdmoj.atlassian.net/browse/LEP-189
Use lograge to eliminate parameter logging in production - we are using the Rails hook to do our own logging, so redacting everything at the start (ala CCQ) wasn't a good fit for this project. Using lograge disables the parameter logging without upsetting our own logging code
=> Lep 189 reduce parameter logging

.circleci/config.yml, Gemfile.lock
No Ticket
'bundle install' in CI would pass even if Gemfile and Gemfile.lock are out of step. This adds the 'frozen' flag to the bundle install command so that this cannot happen in the future
=> Fix bundle install so that it fails if Gemfile.lock is out of step

Gemfile, Gemfile.lock, Guardfile
No Ticket
Add guard bundler so that when gems are updated, guard understands and reloads the bundle
=> Add guard bundler to improve guard experience

app/lib/swagger_docs.rb, spec/requests/swagger_docs/v6/full_assessment_spec.rb, spec/requests/swagger_docs/v7/full_assessment_spec.rb, swagger/v6/swagger.yaml, swagger/v7/swagger.yaml
Starting to implement [ideas for how we should document the API](https://dsdmoj.atlassian.net/wiki/spaces/EPT/pages/4468244596/API+documentation)
I can see this is the start of a fair amount of duplication of descriptions across these two files:
* spec/requests/swagger_docs/v6/full_assessment_spec.rb
* spec/requests/swagger_docs/v7/full_assessment_spec.rb
So if there's a better way to do this, do let me know.
No Jira ticket
---
- PR description - summarizes *what* changed and *why*, …
=> API docs - partner reference to guidance

app/lib/swagger_docs.rb, swagger/v6/swagger.yaml, swagger/v7/swagger.yaml
When using "$ref" in the schema, there is a bug in the Swagger web page that hides sibling properties, such as the field's description.
This PR fixes it by introducing the "oneOf" extra level of abstraction, as discovered by @starswan [here](https://github.com/ministryofjustice/cfe-civil/pull/242#discussion_r1284332230). It's a bit messy, but preferable I think to display the descriptions.
Before:
After:
Jira ticket: [LEP-305](https://dsdmoj.atlassian.net/browse/LEP-305)
---
- PR …
=> LEP-305 Fix Swagger web page displaying the description/example for several fields

app/models/request_log.rb, app/services/redact_service.rb, spec/models/request_log_spec.rb, spec/requests/v6/assessments_controller/simple_spec.rb
[LEP-308](https://dsdmoj.atlassian.net/browse/LEP-308)
`RedactService.redact_old_client_refs` is throwing error while redacting  assessment object with missing `client_reference_id` (as `client_reference_id` is optional attribute in request)
Solution: 
Filter `RequestLog` and then apply redaction
Slack: https://mojdt.slack.com/archives/C04T88Q1B61/p1691374001872429
[LEP-308]: https://dsdmoj.atlassian.net/browse/LEP-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-308 check client_reference_id before redacting

app/lib/swagger_docs.rb, swagger/v6/swagger.yaml, swagger/v7/swagger.yaml
[LEP-305](https://dsdmoj.atlassian.net/browse/LEP-305)
The [previous PR](https://github.com/ministryofjustice/cfe-civil/pull/265) broke the example JSON request, that gets displayed in the Swagger web page:
Submitting it gave validation errors - the currency values were coming out as `"string"`.
e.g. `The property '#/dependants/0/assets_value' of type string did not match any of the required schemas. The schema specific errors were:\n\n    - oneOf #0:\n        - The property '#/dependants/0/assets_value' of type string did not match the following type: number\n    - oneOf #1:\n        - The property '#/dependants/0/assets_value' value \"string\" did not match the regex '^[-+]?\\d+(\\.\\d{1,2})?$'"`
This PR fixes those example values:
and it now submits ok.
---
Before you ask people to …
=> LEP-305 Fix for swagger example being made invalid

app/lib/person_disposable_income_subtotals.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/outgoings_collator.rb, app/services/collators/regular_outgoings_collator.rb, app/services/decorators/v6/disposable_income_decorator.rb, app/services/decorators/v6/disposable_income_result_decorator.rb, db/migrate/20230815143445_remove_maintenance_out_columns_from_from_disposable_income_summary.rb, db/schema.rb, spec/factories/disposable_income_summary_factory.rb, spec/services/collators/disposable_income_collator_spec.rb, spec/services/collators/regular_outgoings_collator_spec.rb, spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
[LEP-271](https://dsdmoj.atlassian.net/browse/LEP-271)
Remove columns from disposable_income_summaries table
- maintenance_out_cash
- maintenance_out_bank
- maintenance_out_all_sources
[LEP-271]: https://dsdmoj.atlassian.net/browse/LEP-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-271 - remove maintenance_out outputs from disposable_income_summary

.circleci/config.yml
---
CCQ is updating its ruby version, this PR is to make sure that the end to end tests on circleCI do not break for cfe-civil after this change.
=> EL-1078 update ruby version used by circleci to match CCQ version

app/services/capital_collator_and_assessor.rb, app/services/summarizers/assessment_proceeding_type_summarizer.rb, app/services/summarizers/capital_summarizer.rb, app/services/summarizers/disposable_income_summarizer.rb, app/services/summarizers/gross_income_summarizer.rb, app/services/summarizers/main_summarizer.rb, app/services/workflows/main_workflow.rb, app/services/workflows/non_passported_workflow.rb, spec/services/summarizers/assessment_proceeding_type_summarizer_spec.rb, spec/services/summarizers/disposable_income_summarizer_spec.rb, spec/services/summarizers/gross_income_summarizer_spec.rb, spec/services/summarizers/main_summarizer_spec.rb, spec/services/workflows/main_workflow_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb, spec/services/workflows/passported_workflow_spec.rb
[LEP-228](https://dsdmoj.atlassian.net/browse/LEP-228)
Rename following Accessors to Summarizers
- Assessors::AssessmentProceedingTypeAssessor -> Summarizers::AssessmentProceedingTypeSummarizer
- Assessors::CapitalAssessor -> Summarizers::CapitalSummarizer
- Assessors::DisposableIncomeAssessor -> Summarizers::DisposableIncomeSummarizer
- Assessors::GrossIncomeAssessor -> Summarizers::GrossIncomeSummarizer
- Assessors::MainAssessor -> Summarizers::MainSummarizer
[LEP-228]: https://dsdmoj.atlassian.net/browse/LEP-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LEP-228 rename  some assessors to summarizers

app/services/summarizers/assessment_proceeding_type_summarizer.rb, spec/services/summarizers/assessment_proceeding_type_summarizer_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-334
Refactor proceeding_type_summarizer to remove awkward implicit state
---
=> LEP-334 partial: proceeding_type_summarizer refactor

app/services/creators/disposable_income_eligibility_creator.rb, config/thresholds/mtr-2026.yml, features/mtr/immigration_and_asylum.feature, features/mtr/income_capital_thresholds.feature, spec/services/creators/disposable_income_eligibility_creator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-232
Increase disposable income lower threshold for MTR. We already have a 'lower contribution band' figure, and this threshold is the same value (its the value at which contributions start)
---
=> LEP-232 disposable income lower === top of zero contribution band

app/lib/person_disposable_income_subtotals.rb, app/services/calculators/housing_costs_calculator.rb, app/services/collators/disposable_income_collator.rb, app/services/collators/housing_costs_collator.rb, app/services/collators/regular_outgoings_collator.rb, spec/services/calculators/housing_costs_calculator_spec.rb, spec/services/collators/housing_costs_collator_spec.rb, spec/services/collators/regular_outgoings_collator_spec.rb
No ticket - supporting 2 MTR Phase 2 housing benefit tickets
Rework HousingCostCollator and HousingCostCalculator - the collator now 'collates' (mostly) and all housing costs now come through this route rather than the side-routes of regular and cash transactions (as the data need to be halved when board and lodging is in effect).
---
=> Refactor housing calculations

app/lib/calculation_output.rb, app/services/decorators/v6/assessment_decorator.rb, app/services/decorators/v6/result_summary_decorator.rb, app/services/workflows/main_workflow.rb, app/services/workflows/non_passported_workflow.rb, app/services/workflows/passported_workflow.rb, spec/services/workflows/main_workflow_spec.rb, spec/services/workflows/non_passported_workflow_spec.rb, spec/services/workflows/passported_workflow_spec.rb
move receives_asylum_support and receives_qualifying_benefit out of calculation output
---
=> LEP-345 move applicant flags out of calculation output object

Dockerfile
Upgrade from Alpine 3.17 to [3.18](https://alpinelinux.org/releases/) moves us to the latest minor release. No particular driver for this, apart from staying on top of things.
The other changes are cosmetic, but brings us closer to a Kamal-generated Dockerfile:
https://greg.molnar.io/blog/deploying-a-rails-app-with-kamal/
Kamal seems to be what's [now the default style built into Rails 7.1](https://edgeguides.rubyonrails.org/7_1_release_notes.html#generate-dockerfiles-for-new-rails-applications) so I think it's good to be in line with this.
I've deviated from Kamal in a couple of ways:
* Stick with alpine, as its much smaller than debian (I've added comments)
* Use a numeric user, which is required by Cloud Platform since it runs containers as non-root (I've added a comment)
* Not tackled …
=> Dockerfile updated to Alpine 3.18 and cosmetic improvements

.github/dependabot.yml
No ticket
Dependabot keeps  running at midnight on Sundaysm when our databases are often offline. Change this to 9am on Monday mornings instead
---
=> Run dependabot at 9am on Mondays

.circleci/config.yml, app/controllers/application_controller.rb, app/models/assessment.rb, app/services/creators/assessment_creator.rb, app/services/creators/full_assessment_creator.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/locales/en.yml, spec/lib/disposable_income/subtotals_spec.rb, spec/rails_helper.rb, spec/requests/application_controller_spec.rb, spec/requests/v6/assessments_controller/errors_spec.rb, spec/requests/v6/assessments_controller/simple_spec.rb, spec/services/calculators/council_tax_calculator_spec.rb, spec/services/calculators/pension_contribution_calculator_spec.rb, spec/services/calculators/priority_debt_repayment_calculator_spec.rb, spec/services/remark_generators/orchestrator_spec.rb, spec/spec_helper.rb, spec/support/error_responses.rb
https://dsdmoj.atlassian.net/browse/LEP-393
Catching errors in test/development mode adds a bit of grit to refactoring, as any errors like 'method not found' are converted into 500 errors rather than being left as exceptions for the developer to manage. This changes that behaviour, so that test mode is much easier to work with
---
=> Lep 393 don't capture errors in test mode

lib/tasks/rswag.rake
No ticket
This is an attempt to fix the flakey swaggerization check. It looks like it is possible that running the 'glob' twice could result in the files being returned in a different order (very occasionally) which would result in the array comparison failing. This sorts the array (and makes the rake task a bit more idiomatic) to try and prevent this issue recurring
---
=> Fix flakey swaggerization check

features/mtr/mtr_32_51_subject_matter_of_dispute_disregard.feature, features/mtr/mtr_47_property_disregard_main_home.feature, features/step_definitions/api_request_steps.rb
No ticket
The cucumber step hard-coded the property value rather than passing it in as a parameter
---
=> tweak cucumber fixture to not hard code property value

app/constants/cfe_constants.rb, app/lib/swagger_docs.rb, app/models/proceeding_type.rb, spec/cassettes/LegalFrameworkAPI_ThresholdWaivers/_call/successful_API_call/responds_to_calling_service_with_parsed_response.yml, spec/factories/proceeding_type_factory.rb, spec/models/proceeding_type_spec.rb, spec/services/legal_framework_api/threshold_waivers_spec.rb, swagger/v6/swagger.yaml, swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-407
Document client_involvement_type both in the API and in the code where the valid types are listed.
Extended the LFA VCR test to cover all involvement types to back up hypothesis that waivers only apply when client_involvement_type === 'A' (applicant/claimant/petitioner)
---
=> LEP-407 document and test client involvement types from LFA

README.md, app/services/request_rerunner.rb
No ticket
Use v6 CFE endpoint (v7 now incompatible with old requests) and change readme to reflect 5 minutes rather than 1 hour runtime
---
=> Tidy request rerunner - use v6 API, and change readme

.circleci/config.yml, app/controllers/application_controller.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
No Ticket
Turns out that the work done to fix up the error handling during was exactly flipped - this fixes it
---
=> Test exception settings were the mirror image of correct ones

app/services/calculators/housing_costs_calculator.rb, app/services/calculators/state_benefits_calculator.rb
Following on from LEP-410, a few more adjustments to language to hopefully make this code clearer.
* `housing_benefit_in_standard_calculation` - "standard calculation" is a made-up term...sorry - let's use the specific terms "gross_income_and_allowed_housing_costs" 
* `housing_benefit` variable was not the amount that the person receives in housing benefit, in the case of post-MTR, so confusing. Renamed to `housing_benefit_to_subtract` to make it clear this figure was the amount of housing benefit that is subtracted from housing costs to get 'allowed housing costs'.
* Reworked the comments about board and lodging
https://dsdmoj.atlassian.net/browse/LEP-410
---
=> LEP-410 Housing Benefit - more renames

config/database.yml
No Ticket
Reduce the pool size from 25 back down to the default. It seems to have no bearing on production performance (which is a few hundred requests / day) and slows down testing
---
=> Reduce database pool size as it slows everything down

config/initializers/rswag_api.rb, spec/spec_helper.rb
No Tioket
Remove rswag deprecation warning
---
=> Fix swagger root deprecation warning

Gemfile, Gemfile.lock, app/constants/cfe_constants.rb, app/services/govuk_bank_holiday_retriever.rb, config/environments/test.rb, spec/services/govuk_bank_holiday_retriever_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-464
Remove Faraday caching middleware as bank holidays are no longer marked cachable
---
=> Lep 464 fix bank holiday caching

.circleci/config.yml, deploy/helm/templates/_envs.tpl
https://dsdmoj.atlassian.net/browse/LEP-415
Enable YJIT, as it will be enabled by default on ruby 3.3 
Performance was measured using the request_rerunner, but showed no noticeable improvements. It seems likely that performance is still dominated by i/o (database access)
---
=> LEP-415 enable YJIT

Gemfile, Gemfile.lock
No ticket
Google drive and the roo spreadsheet parser are not needed in production builds, so remove them
---
=> Remove spreadsheet parser from production

README.md, app/models/threshold.rb, config/application.rb, spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-495
Add a config variable which allows 'promotion' of a future config file into todays date. Will be used to create an MTR test environment where the variable is set to mtr-2026.yml 
The existing code had to be re-worked to make it testable - it used a class-scope lazy loaded 'instance' variable which could never be re-loaded
---
=> LEP-495 add a flag to enable a future threshold file to be in scope

infrastructure/cfe-civil-uat/pods-dashboard.yaml
https://dsdmoj.atlassian.net/browse/LEP-493
Phase II of Prometheus integration - add extra Grafana dashboard to display average request time
---
=> LEP-493 Add a new panel to grafana dashboard

.circleci/config.yml
No ticket
The 'deploy_main' target currently fails to deploy (something) as the duplicate build_and_push_staging_mtr step definition is missing 
---
=> fix deploy_main target to have build_and_push_staging_mtr

.circleci/config.yml
No ticket
Re-enable undercover after 29th February issue
---
=> re-enable undercover

deploy/helm/values/production.yaml
No ticket
USE_TEST_THRESHOLD_DATA seems to be set true on production - don't think it should be
---
=> set use test data to false on production

.circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-508
staging_mtr and production need to have their own tags, so that they do not share an ECR lifecycle rule, otherwise lots of builds of one will cause the lifecycle rule to delete the in-use image for the other.
Also rename 'dev' to 'uat' so that we consistently tag by environment name. Will change the lifecycle rules to match.
---
=> LEP-508 Docker images tagging - staging_mtr and production

deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-501
There is an issue with metabase in staging. To try and fix this i am deploying manually to staging. However I am getting an error:
`ERROR: relation "core_user" already exists`
Which may be due to the existing metabase deployment in staging, deleting this pod manually is not possible so I want to remove it from staging until we can figure out the issue.
=> LEP-501 part 2: turn off metabase in staging to manually test deploys

.circleci/config.yml
Otherwise the tag is moved from previous images of the branch. So all the previous images of the branch are missed when the ECR image lifecycle_policy does its clean up.
https://dsdmoj.atlassian.net/browse/LEP-508
You can [view the ECR images](https://dsdmoj.atlassian.net/wiki/spaces/EPT/pages/4799397892/ECR+images) and this is what this branch's image looks like, including the revised tag:
`aws ecr describe-images --repository-name laa-eligibility-platform/cfe-civil-ecr |less`
=> LEP-508 ECR branch-name tags made unique

app/controllers/status_controller.rb
While looking at the healthcheck Steven and I noticed a potential bug. The two checks should probably be joined using && as opposed to being 2 different checks we also identified a ruby specific way to check a table exists so this replaces :
`RequestLog.first.present?` with `table_exists?`
---
=> Database Health Check

README.md
Remove FUTURE_THRESHOLD_FILE from .env setup, as this isn't required for the spreadsheet integration tests to pass, And will cause tests to fail when running bundle exec rspec or bundle exec cucumber.
This could be confusing for new developers.
Move the instructios for using the threshold file when running locally to the Test threshold data section instead.
https://dsdmoj.atlassian.net/browse/LEP-XXX
---
=> Update readme to clarify integration test setup

.circleci/config.yml, features/BBB_CFE_Integration_Test_V3_Passported/P1-3-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P1-4-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P3-1-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P3-2-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P4-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P5-V5.feature, features/BBB_CFE_Integration_Test_V3_Passported/P6-V5.feature, features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP1-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP2-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP3-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP4-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP5-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortNP6-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP1-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP2-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP3-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP4-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP5-V5.feature, features/DDD_CFE_Integration_Test_V3_Mortgage/MortP6-V5.feature, features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/EL-2156
- If applied, this converts passported (DDD) spreadsheet tests to cucumber
- Added a new cucumber step definition `I add a benefits regular_transactions of {float} per month of credit`
- This also formats the BBB & CCC cucumber tests
In addition this change disables `undercover` code coverage as it was behaving oddly when adding a new method to `features/step_definitions/api_request_steps.rb`. The coverage complaint realted to an existing method already used in a test, not the new one added. Before disabling `undercover` I had tried the following:
- adding a filter to `spec_helper` to ignore step definitions & features folder
- adding `# :nocov:` to various parts of `features/step_definitions/api_request_steps.rb`
---
Author: (before you ask …
=> EL-2156: Convert passported (DDD) tests to cucumber

README.md, config/thresholds/2025-04-07.yml, config/thresholds/values.yml, features/dependant/dependant_income.feature, features/partner/partner_assessment.feature, spec/models/threshold_spec.rb
Add new thresholds configuration file with uprated partner and dependant allowances
https://dsdmoj.atlassian.net/browse/LEP-2127
Can be tested using using swagger and the request details I have added to the ticket.
The threshold value file changes are not loaded if test_only: true is added, I have commented this out to allow for testing, but we should probably add it before merging (however, we would then need to remove it again before the 7/4). That is why I have added the do not merge label.
Adding futureFile: '2025-04-07.yml' overrides the effective date and sets it to today's date again to allow for testing. If necessary for testing purposes I think we can set this to be a different date in values.yml.
I think our readme is slightly confusing around threshold value file testing and …
=> EL-2127: add new thresholds configuration file.

spec/cassettes/LegalFrameworkAPI_ThresholdWaivers/_call/successful_API_call/responds_to_calling_service_with_parsed_response.yml, spec/cassettes/V6_AssessmentsController/POST_/create/non_means_tested/certificated/when_applicant_over_18/is_not_eligible.yml, spec/services/legal_framework_api/threshold_waivers_spec.rb
`full_s8_only` is an obsolete value, it was implemented so we could release the section Section 8 matter type in two phases and the need was removed many years, and matter types, ago.
It has been removed from LFA so this PR is to reduce any unnecessary complexity in the CFE code base
https://dsdmoj.atlassian.net/browse/AP-5044
While re-recording the cassettes it updated some other changed values
---
=> AP-5044: Remove the full_s8_only from LFA

.github/dependabot.yml
Group bundler dependabot prs to make reviewing/merging quicker.
I don't think we see many docker or github-actions dependabots, so I don't think it is worth grouping these currently.
=> CHORE: group bundler dependabots

.rubocop.yml
This should make local rubocop runs less noisy
---
=> Chore: Remove rubocop warning

bin/uat_deploy
Amend postgresql chart to use bitnami legacy image repository
https://dsdmoj.atlassian.net/browse/AP-6214
Following the deprecation of support for such images by bitnami.
see [bitnami chart issue](https://github.com/bitnami/charts/issues/35164)
```sh
Containers:
postgresql:
Container ID:   containerd://redacted
Image:          docker.io/bitnami/postgresql:14.5.0-debian-11-r35
Image ID:       docker.io/bitnami/postgresql@sha256:<redacted>
```
```sh
Containers:
postgresql:
Container ID:   containerd://redacted
Image:          docker.io/bitnamilegacy/postgresql:14.5.0-debian-11-r35
Image ID:       docker.io/bitnamilegacy/postgresql@sha256:<redacted>
```
=> AP-6214: Amend postgresql chart to use bitnami legacy image repository

README.md
CHORE: update readme to remove details of port forward pod.
This was deleted in this pr https://github.com/ministryofjustice/cfe-civil/pull/850
- Tests and rubocop should be passing: `bundle exec rake`.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) should be followed.
- You should have looked at the diff against main and ensured that nothing unexpected is included in …
=> CHORE update readme to remove details of port forward pod
