ministryofjustice/cfe-civil

- README.md
- spec/services/calculators/housing_costs_calculator_spec.rb
LEP-37 - changes to CFE classic
> LEP-37 CFE classic changes

- .circleci/config.yml
- infrastructure/uat/ingress-dashboard.yaml
- infrastructure/uat/pods-dashboard.yaml
https://dsdmoj.atlassian.net/browse/LEP-38
Add Grafana dashboards copied from CCQ without changes
> LEP-38 Grafana Dashboards

- .circleci/config.yml
- bin/delete_dependabot_deployment
- bin/delete_ecr_images
- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-39
> LEP-39 Test for new ECR repo

- .circleci/config.yml
- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-39
cfe-civil circle CI config
> LEP-39 circle config for staging and production

- app/lib/person_capital_subtotals.rb
- spec/requests/swagger_docs/v5/applicants_spec.rb
- spec/requests/swagger_docs/v5/cash_transactions_spec.rb
- spec/requests/swagger_docs/v5/employments_spec.rb
- spec/requests/swagger_docs/v5/full_assessment_spec.rb
- spec/requests/swagger_docs/v5/outgoings_spec.rb
- spec/requests/swagger_docs/v5/partner_financials_spec.rb
- spec/swagger_helper.rb
- swagger/v5/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-113
Add documentation around proceeding type. Re-organise field documentation to be in a logical order where related fields are grouped together. Where 1 field is the sum of 2 others, say so explicitly
> LEP-113 document proceeding type

- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
[LEP-151](https://dsdmoj.atlassian.net/browse/LEP-151)
Setup Sentry in staging and prod environments to get  sentry alerts on slack for Ruby exceptions
[LEP-151]: https://dsdmoj.atlassian.net/browse/LEP-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-151 enable sentry for staging and production

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-105
Draft for testing - run CCQ tests against the current branch
> LEP-105 Run CCQ E2E tests inside CFE pipeline with latest codebase

- app/controllers/dependants_controller.rb
- app/models/assessment.rb
- app/services/creators/eligibilities_creator.rb
- app/services/creators/full_assessment_creator.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/calculators/housing_costs_calculator_spec.rb
- spec/services/collators/housing_costs_collator_spec.rb
- spec/services/collators/outgoings_collator_spec.rb
- spec/services/creators/dependants_creator_spec.rb
- spec/services/creators/eligibilities_creator_spec.rb
- spec/services/creators/gross_income_eligibility_creator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-137
Rename 'dependants' as 'client_dependants' so that it is clear in the code that partner_dependants are excluded from this relationship
> LEP-137 refactor dependants into client_dependants to avoid confusion

- app/models/gross_income_summary.rb
- app/services/calculators/housing_costs_calculator.rb
- app/services/calculators/monthly_cash_transaction_amount_calculator.rb
- app/services/collators/childcare_collator.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/gross_income_collator.rb
- app/services/collators/housing_costs_collator.rb
- app/services/collators/legal_aid_collator.rb
- app/services/collators/maintenance_collator.rb
- app/services/collators/outgoings_collator.rb
- spec/services/calculators/housing_costs_calculator_spec.rb
- spec/services/collators/childcare_collator_spec.rb
- spec/services/collators/housing_costs_collator_spec.rb
- spec/services/collators/legal_aid_collator_spec.rb
- spec/services/collators/maintenance_collator_spec.rb
- spec/services/collators/outgoings_collator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-124
Move cash transactions up one level so that we don't need to pass gross_income_summary to a method that just wants cash transactions
> LEP-124 move cash transactions up one level

- spec/requests/v6/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-103
Added test for unspecified source to v6 endpoint. Cucumber test already present, so not changed
> LEP-103 added unspecified source to irregular payments received

- deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-187
Move staging instance to production Legal Framework API instance to prevent crashes
> LEP-187 use production Legal Framework API for staging instance

- app/controllers/application_controller.rb
- app/services/request_logger.rb
- features/step_definitions/api_request.rb
- features/support/request_support_methods.rb
- spec/requests/v6/assessments_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-183
Redact dates of birth when writing log records
> LEP-183 Redact dates of birth for applicant/partner and their dependants

- app/lib/calculation_output.rb
- app/lib/capital_subtotals.rb
- app/lib/person_capital_subtotals.rb
- app/services/capital_collator_and_assessor.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/decorators/v6/assessment_decorator_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
- spec/services/workflows/passported_workflow_spec.rb
- spec/spec_helper.rb
[LEP-207](https://dsdmoj.atlassian.net/browse/LEP-207)
Return vehicles in response when disposable income test is ineligible
[LEP-207]: https://dsdmoj.atlassian.net/browse/LEP-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-207 return vehicle in response

- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
- deploy/helm/values/uat.yaml
https://dsdmoj.atlassian.net/browse/LEP-206
> LEP-206 re-enable sentry on UAT

- features/employment/tax_refunds.feature
- features/step_definitions/api_request.rb
- features/step_definitions/remarks.rb
- features/support/response_support_methods.rb
https://dsdmoj.atlassian.net/browse/LEP-201
Add cucumber tests for tax refund and multiple employment scenarios
> LEP-201 add Cucumber tests for tax refund and multiple employments

- app/models/self_employment_income.rb
- app/services/utilities/monthly_amount_converter.rb
- spec/services/workflows/non_passported_workflow_spec.rb
- swagger/v6/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-212
> LEP-212 support annual income frequency for self employment

- app/services/concerns/exemptable.rb
- app/services/remark_generators/amount_variation_checker.rb
- app/services/remark_generators/base_checker.rb
- app/services/remark_generators/frequency_checker.rb
- app/services/remark_generators/multi_benefit_checker.rb
- app/services/remark_generators/orchestrator.rb
- app/services/remark_generators/residual_balance_checker.rb
- app/services/workflows/main_workflow.rb
- spec/requests/v6/assessments_controller_spec.rb
- spec/services/remark_generators/amount_variation_checker_spec.rb
- spec/services/remark_generators/frequency_checker_spec.rb
- spec/services/remark_generators/multi_benefit_checker_spec.rb
- spec/services/remark_generators/orchestrator_spec.rb
- spec/services/remark_generators/residual_balance_checker_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-172
Convert remarks orchestrator to create remarks for partner data as well as applicant data
> LEP-172 remarks for partner variations to match those for applicant

- Changelog.md
https://dsdmoj.atlassian.net/browse/LEP-75
Create a changelog
> LEP-75 first cut - dates and releases

- spec/factories/person_details_factory.rb
- spec/integration/policy_disregards_spec.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller_spec.rb
- spec/services/collators/disposable_income_collator_spec.rb
- spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
- spec/spec_helper.rb
- swagger/v6/swagger.yaml
Fix defective test found during LEP-218 - also remove duplication using person_data factory
> fix defective test

- app/controllers/v6/assessments_controller.rb
- app/lib/employment_income_subtotals.rb
- app/lib/person_gross_income_subtotals.rb
- app/models/employment_income.rb
- app/models/employment_or_self_employment_income.rb
- app/models/person_data.rb
- app/models/self_employment_income.rb
- app/models/standard_employment_income.rb
- app/services/calculators/employment_income_calculator.rb
- app/services/calculators/multiple_employments_calculator.rb
- app/services/collators/gross_income_collator.rb
- app/services/decorators/v6/assessment_decorator.rb
- app/services/decorators/v6/gross_income_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- features/employment/self_employment.feature
- features/step_definitions/api_request.rb
- features/step_definitions/self_employment.rb
- spec/factories/person_details_factory.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller_spec.rb
- spec/services/calculators/employment_income_calculator_spec.rb
- spec/services/calculators/multiple_employments_calculator_spec.rb
- spec/services/collators/gross_income_collator_spec.rb
- spec/services/decorators/v6/assessment_decorator_spec.rb
- spec/services/decorators/v6/gross_income_decorator_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
- spec/spec_helper.rb
- spec/swagger_helper.rb
- swagger/v6/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-218
Rework input and outputs from self-employment to be simpler and more straightforward by removing is_employment boolean
> LEP-218 self employment rework

- Changelog.md
No Jira ticket
Just me meddling
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.
> Reword bug description

- app/services/request_logger.rb
- spec/requests/v6/assessments_controller_spec.rb
[LEP-223](https://dsdmoj.atlassian.net/browse/LEP-223)
Log the requests when payload is invalid and required keys are missing 
[LEP-223]: https://dsdmoj.atlassian.net/browse/LEP-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-223 Rescue KeyError (key not found: "applicant")

- app/services/request_logger.rb
- spec/requests/v6/assessments_controller_spec.rb
[LEP-223](https://dsdmoj.atlassian.net/browse/LEP-223)
Check partner object presence before redacting partner's DOB
[LEP-223]: https://dsdmoj.atlassian.net/browse/LEP-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-223 Fix partner dob redact

- app/services/creators/employments_creator.rb
- app/services/creators/gross_income_eligibility_creator.rb
- app/services/creators/regular_transactions_creator.rb
No ticket
Fix up layout issues to allow rubocop 4.11 to pass tests
> Tidy up for rubocop-411

- app/services/redact_service.rb
- app/services/request_logger.rb
- spec/factories/request_log_factory.rb
- spec/requests/v6/assessments_controller_spec.rb
- spec/services/redact_service_spec.rb
[LEP-220](https://dsdmoj.atlassian.net/browse/LEP-220)
Redact `time` in  `timestamp`  while saving API response in DB
[LEP-220]: https://dsdmoj.atlassian.net/browse/LEP-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-220 Redact time in the request_log.response timestamp

- lib/integration_helpers/test_case/v5/remarks_comparer.rb
- lib/integration_helpers/test_case/v5/result_comparer.rb
- spec/integration/test_runner_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-43
> LEP-43 extract comparisons for friendly spreadsheet errors

- app/lib/swagger_docs.rb
- app/services/decorators/v6/property_decorator.rb
- features/controlled_work/property_assessment.feature
- features/disputed_assets/disputed_property.feature
- features/disputed_assets/disputed_vehicle.feature
- features/disputed_assets/multiple_disputed_assets.feature
- features/partner/partner_assessment.feature
- features/pensioner/pensioner_disregard.feature
- features/property/property.feature
- spec/requests/v6/assessments_controller_spec.rb
- spec/services/decorators/v6/property_decorator_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
[LEP-278](https://dsdmoj.atlassian.net/browse/LEP-278)
Return attribute "subject_matter_of_dispute" in response
- assessment > capital > capital_items > properties > main_home > subject_matter_of_dispute
- assessment > capital > capital_items > properties > additional_properties[] > subject_matter_of_dispute
- assessment > partner_capital > capital_items > properties > main_home > subject_matter_of_dispute
- assessment > partner_capital > capital_items > properties > additional_properties[] > subject_matter_of_dispute
[LEP-278]: https://dsdmoj.atlassian.net/browse/LEP-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-278 - return attribute "subject_matter_of_dispute" in properties response

- app/lib/employment_income_subtotals.rb
- app/lib/person_gross_income_subtotals.rb
- app/lib/person_wrapper.rb
- app/services/calculators/childcare_eligibility_calculator.rb
- app/services/calculators/multiple_employments_calculator.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/calculators/childcare_eligibility_calculator_spec.rb
- spec/services/collators/outgoings_collator_spec.rb
[LEP-273](https://dsdmoj.atlassian.net/browse/LEP-273)
- Simplify PersonWrapper class and remove is_student? and in_work? methods
[LEP-273]: https://dsdmoj.atlassian.net/browse/LEP-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-273 refactor and move methods is_student? and in_work? from PersonWrapper

- features/employment/child_care.feature
- features/step_definitions/api_request.rb
https://dsdmoj.atlassian.net/browse/LEP-274
Add cucumber tests for submitting child care costs via both routes
> LEP-274 Add cucumber test for child care submitted both ways

- Changelog.md
- app/services/creators/partner_financials_creator.rb
- features/partner/partner_cash_transactions.feature
- features/step_definitions/api_request.rb
- features/step_definitions/cash_transactions.rb
- features/support/response_support_methods.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- spec/requests/v6/assessments_controller_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-83
Added partner cash transactions
> LEP-83 Added cash transactions for partner

- Changelog.md
There was a gap, after we automated the releases, so stopped writing the changelog, until recently we discussed the need to write changelog entries as part of creating PRs.
No ticket
---
> Fill in missing changelog entries

- app/lib/person_disposable_income_subtotals.rb
- app/models/assessment.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/outgoings_collator.rb
- app/services/collators/regular_outgoings_collator.rb
- app/services/concerns/exemptable.rb
- app/services/decorators/v6/disposable_income_decorator.rb
- app/services/remark_generators/amount_variation_checker.rb
- app/services/remark_generators/base_checker.rb
- app/services/remark_generators/frequency_checker.rb
- app/services/remark_generators/orchestrator.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- db/migrate/20230710092930_remove_childcare_from_disposable_income_summary.rb
- db/schema.rb
- spec/factories/disposable_income_summary_factory.rb
- spec/services/collators/disposable_income_collator_spec.rb
- spec/services/collators/regular_outgoings_collator_spec.rb
- spec/services/remark_generators/amount_variation_checker_spec.rb
- spec/services/remark_generators/frequency_checker_spec.rb
- spec/services/remark_generators/multi_benefit_checker_spec.rb
- spec/services/remark_generators/orchestrator_spec.rb
- spec/services/workflows/main_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-164
> LEP-164 Remove child_care_bank, child_care_cash and child_care_all_sources from database

- db/migrate/20230720075220_convert_request_log_to_json_b.rb
- db/schema.rb
https://dsdmoj.atlassian.net/browse/LEP-289
> LEP-289 convert JSON columns to JSONB

- Changelog.md
- app/services/creators/partner_financials_creator.rb
- features/partner/partner_other_income.feature
- features/step_definitions/api_request.rb
- features/step_definitions/other_incomes.rb
- features/support/response_support_methods.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller_spec.rb
- swagger/v6/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-84
Add 'other incomes' section to partner submission for use by Civil Apply
> LEP-84 Partner other incomes

- app/lib/swagger_docs.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-263
> LEP-263 Add documentation for housing cost type

- Gemfile
- Gemfile.lock
- README.md
- app/models/application_record.rb
- app/models/request_log.rb
- app/models/request_log_base.rb
- app/services/request_rerunner.rb
- config/database.yml
- config/environments/remote_database.rb
- db/migrate/20220915153334_remove_unused_cols.rb
- lib/tasks/rerun_requests.rake
- spec/factories/request_log_factory.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-282
> LEP-282 Request re-runner written in Ruby

- Guardfile
- app/lib/swagger_docs.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller/errors_spec.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/swagger_helper.rb
- swagger/v6/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-279
Add tightened validation from v7 controller into v6
> LEP-279 tighten validation in v6 controller

- app/lib/person_disposable_income_subtotals.rb
- app/services/collators/childcare_collator.rb
- app/services/collators/dependants_allowance_collator.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/outgoings_collator.rb
- app/services/collators/regular_outgoings_collator.rb
- app/services/decorators/v6/disposable_income_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- db/migrate/20230721152030_remove_rent_or_mortgage_from_disposable_income_summary.rb
- db/schema.rb
- spec/factories/disposable_income_summary_factory.rb
- spec/services/collators/disposable_income_collator_spec.rb
- spec/services/collators/regular_outgoings_collator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-269
Remove rent_or_mortgage fields from disposable income summary
> LEP-269 Rent or mortgage from disposable_income_summary

- app/lib/swagger_docs.rb
- app/lib/swagger_loader.rb
- app/validators/json_swagger_validator.rb
- spec/lib/swagger_loader_spec.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- spec/spec_helper.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-293
Document complete response schema by setting additionalProperties: false everywhere
> LEP-293 complete documentation of response schema 

- spec/spec_helper.rb
Reduce branch coverage for production release
> fix branch coverage

- README.md
I need this improved info about where the swagger source files are...
No Jira ticket
---
> Improve README description of the swagger files

- app/constants/cfe_constants.rb
- app/services/redact_service.rb
- app/services/remarks.rb
- app/services/request_logger.rb
- spec/factories/request_log_factory.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/redact_service_spec.rb
[LEP-288](https://dsdmoj.atlassian.net/browse/LEP-288)
Redacted `assessment > remarks` in response
[LEP-288]: https://dsdmoj.atlassian.net/browse/LEP-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-288 Redact client ids in response (assessment > remarks)

- Gemfile
- Gemfile.lock
- features/step_definitions/api_request.rb
No Ticket
put back spring as it appears to be needed for IntelliJ to work properly with cucumber
> Put back spring

- app/lib/swagger_docs.rb
- app/services/request_logger.rb
- spec/requests/v6/assessments_controller/errors_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-217
Validate submission date - essentially stop the logger crashing on an invalid date (which made the existing validation code kick in correctly)
> LEP-217 validate dateness of submission date

- README.md
- app/services/redact_service.rb
- deploy/helm/templates/cronjob-maintenance-tasks.yaml
- lib/tasks/cull_stale_assessments.rake
- lib/tasks/maintenance_tasks.rake
- spec/requests/v6/assessments_controller/simple_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-192
> LEP-192 add redacting of old client ids to maintenance tasks list

- app/controllers/application_controller.rb
https://dsdmoj.atlassian.net/browse/LEP-205
> LEP-205 don't send sentry alerts for 422 errors

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-208
> LEP-208 notify in Slack when production deploy fails

- app/lib/person_disposable_income_subtotals.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/outgoings_collator.rb
- app/services/collators/regular_outgoings_collator.rb
- app/services/decorators/v6/disposable_income_decorator.rb
- db/migrate/20230811075349_remove_legal_aid_from_disposable_income_summary.rb
- db/schema.rb
- spec/factories/disposable_income_summary_factory.rb
- spec/services/collators/disposable_income_collator_spec.rb
- spec/services/collators/regular_outgoings_collator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-270
Remove legal_aid cash, bank and all_sources from disposable_income_summary
> Lep 270 remove legal aid outputs from disposable_income_summary

- app/services/request_logger.rb
- app/services/request_rerunner.rb
- config/environments/development.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/redact_service_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-283
The redaction code for date of birth had a subtle bug - it either moved the date to the submission date, or 1 year before which has the unfortunate behaviour of aging the person by 1 year.
> lep-283 Fix date of birth redaction issue

- Changelog.md
[LEP-190](https://dsdmoj.atlassian.net/browse/LEP-190)
Should probably add this subtle change to the calculation to the changelog
---
[LEP-190]: https://dsdmoj.atlassian.net/browse/LEP-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-190 Add the release to the changelog

- app/services/redact_service.rb
- app/services/request_logger.rb
No Ticket
Move redact_dob and redact_time into the RedactService. It feels awkward calling the RequestLogger from the RedactService to do redactions - this feels more logical (and puts Redaction code into the RedactService)
> Move redact_dob and redact_time into RedactService

- app/services/redact_service.rb
- app/services/request_logger.rb
No ticket
Move updated_remarks from RequestLogger into RedactService as it is to do with Redaction
> Move updated_remarks into RedactService

- Gemfile
- Gemfile.lock
No ticket
Remove an unused gem from the Gemfile. It appears to be unused, so should not be included in the bundle
> remove unused active record serializers gem

- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
- deploy/helm/values/uat.yaml
[LEP-316](https://dsdmoj.atlassian.net/browse/LEP-316)
|     ENV       |       OLD      |      NEW     |
| ---------   | ----------- | ----------- |
| staging      | https://legal-framework-api.cloud-platform.service.justice.gov.uk      |  http://legal-framework-api.legal-framework-api-production.svc.cluster.local      |
| uat             | https://legal-framework-api-staging.cloud-platform.service.justice.gov.uk    | http://legal-framework-api.legal-framework-api-staging.svc.cluster.local      |
| production |  https://legal-framework-api.cloud-platform.service.justice.gov.uk | http://legal-framework-api.legal-framework-api-production.svc.cluster.local        |
[LEP-316]: https://dsdmoj.atlassian.net/browse/LEP-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
>  LEP-316 Update URLs

- app/lib/calculation_output.rb
- app/lib/disposable_income_subtotals.rb
- app/services/assessors/disposable_income_assessor.rb
- app/services/decorators/v6/disposable_income_result_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- db/migrate/20230816071022_remove_disposable_result_data.rb
- db/schema.rb
- spec/factories/disposable_income_summary_factory.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/assessors/disposable_income_assessor_spec.rb
- spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-87
Remove assessment result fields from disposable income summary
> LEP-87 remove disposable result from disposable income summary

- app/models/request_log.rb
- app/services/redact_service.rb
- lib/tasks/maintenance_tasks.rake
- spec/models/request_log_spec.rb
[LEP-303](https://dsdmoj.atlassian.net/browse/LEP-303)
Delete request_log records older than 5 years
[LEP-303]: https://dsdmoj.atlassian.net/browse/LEP-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-303 Delete 5 years old logs

- app/services/redact_service.rb
- app/services/request_logger.rb
- spec/factories/request_log_factory.rb
- spec/services/redact_service_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-281
> LEP-281 redact response dob

- app/lib/calculation_output.rb
- app/lib/disposable_income_subtotals.rb
- app/lib/person_disposable_income_subtotals.rb
- app/services/capital_collator_and_assessor.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/regular_outgoings_collator.rb
- app/services/decorators/v6/applicant_disposable_income_result_decorator.rb
- app/services/decorators/v6/disposable_income_result_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- app/services/workflows/passported_workflow.rb
- db/migrate/20230816091942_remove_totals_from_disposable_summary.rb
- db/schema.rb
- spec/factories/disposable_income_summary_factory.rb
- spec/services/assessors/disposable_income_assessor_spec.rb
- spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
- spec/services/collators/disposable_income_collator_spec.rb
- spec/services/collators/regular_outgoings_collator_spec.rb
- spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-299
Removed totals (including combined_totals) fields from disposable_income_summaries table
> Lep 299 totals from disposable income summary

- config/thresholds/mtr-2026.yml
- config/thresholds/values.yml
- features/mtr/gross_income.feature
https://dsdmoj.atlassian.net/browse/LEP-230
> LEP-230 Create MTR thresholds file and change gross_income threshold

- app/controllers/v6/assessments_controller.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
No Ticket
Bug fix to allow capitals to be passed in as string values
> Fix capital values being passed as strings rather than numbers

- docs/pull_request_template.md
> PR template - add note about secrets

- spec/requests/v6/assessments_controller/simple_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-332
Add high-level test for tax and NI refunds, as this was missing and is useful for payments refactoring
> LEP-322 - add new test for NI and tax refunds

- docs/pull_request_template.md
No ticket
PRs will now look like this:
---
> Pull Request template - migration reminder, checkboxes

- db/migrate/20230822150822_remove_capital_items_table.rb
> fix rollback migration bug

- app/services/calculators/dependant_allowance_calculator.rb
- spec/services/calculators/dependant_allowance_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-320
Suggested tidy up of child dependants code to make it more readable
---
> LEP-320 suggested tidy up

- app/services/calculators/dependant_allowance_calculator.rb
- features/dependant/dependant_income.feature
- features/dependant/dependant_monthly_income.feature
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/calculators/dependant_allowance_calculator_spec.rb
[LEP-320](https://dsdmoj.atlassian.net/browse/LEP-320)
Deduct dependant’s(child under 15 years old) income from Dependant Allowance
[LEP-320]: https://dsdmoj.atlassian.net/browse/LEP-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LEP-320 - deducted child_under_15's income from dependent allowance

- spec/requests/v6/assessments_controller/simple_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-322
Added extra test to support multiple employment refactoring
---
> added test for LEP-322

- app/lib/employment_income_subtotals.rb
- app/services/calculators/employment_income_calculator.rb
- app/services/calculators/employment_monthly_value_calculator.rb
- app/services/calculators/multiple_employments_calculator.rb
- app/services/calculators/tax_ni_refund_calculator.rb
- app/services/collators/gross_income_collator.rb
- app/services/decorators/v6/gross_income_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/calculators/multiple_employments_calculator_spec.rb
- spec/services/calculators/tax_ni_refund_calculator_spec.rb
- spec/services/decorators/v6/gross_income_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-322
Pre-refactor to stop altering payment data in-situ in the database, to help enable LEP-322
> Lep 322 return payment data

- app/services/decorators/v6/applicant_gross_income_result_decorator.rb
- app/services/decorators/v6/gross_income_result_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- spec/services/decorators/v6/applicant_gross_income_result_decorator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-334
---
> LEP-334 split out Applicant part of GrossIncomeResult decorator

- app/lib/calculation_output.rb
- app/models/applicant.rb
- app/services/decorators/v6/assessment_decorator.rb
- app/services/decorators/v6/remarks_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- app/services/summarizers/main_summarizer.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- app/services/workflows/passported_workflow.rb
- db/migrate/20230911161839_remove_column_assessment_result_from_assessments.rb
- db/schema.rb
- spec/services/decorators/v6/assessment_decorator_spec.rb
- spec/services/summarizers/main_summarizer_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
- spec/services/workflows/passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-343
---
> LEP-343  Return assessment_result from calculation_output instead of DB

- spec/fixtures/partner_financials.json
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
This is improving our API docs, in preparation for Civil Apply using the "partner" API next quarter.
No ticket
---
> Example request is filled out more, to demo all the "partner" fields

- Changelog.md
- app/models/dependant.rb
- app/services/creators/gross_income_eligibility_creator.rb
- config/thresholds/2018-04-08.yml
- config/thresholds/2019-04-08.yml
- config/thresholds/2020-04-06.yml
- config/thresholds/2021-01-28.yml
- config/thresholds/2021-04-12.yml
- config/thresholds/2022-04-11.yml
- config/thresholds/2023-04-10.yml
- config/thresholds/mtr-2026.yml
- spec/services/creators/gross_income_eligibility_creator_spec.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-233
Change algorithm to use percentage uplift rather than threshold uplift, all based on age of dependant +- 14 years
---
> LEP-233 New gross income threshold raising

- config/thresholds/mtr-2026.yml
- features/mtr/property_disregard_main_home.feature
- spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-245
---
> LEP-245 Increase Property Disregard Main Home Threshold

- config/thresholds/mtr-2026.yml
- features/mtr/subject_matter_of_dispute_disregard.feature
- spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-248
---
> LEP-248 Remove cap on SMOD

- features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature
- features/mtr/equivilization.feature
- features/partner/partner_assessment.feature
- features/step_definitions/api_request.rb
https://dsdmoj.atlassian.net/browse/LEP-233
Added a cucumber test to show equivalization implementation
---
> LEP-233 added cucumber test

- features/mtr/pensioner_capital_disregard.feature
- features/step_definitions/api_request.rb
https://dsdmoj.atlassian.net/browse/LEP-246
Add cucumber tests
---
> LEP-246 Add spec

- app/models/dependant.rb
- app/services/assessors/property_assessor.rb
- app/services/calculators/dependant_allowance_calculator.rb
- app/services/utilities/number_utilities.rb
- config/thresholds/mtr-2026.yml
- features/CCC_CFE_Integration_Test_V3/NPE10-4-V5.feature
- features/dependant/dependant_income.feature
- features/dependant/dependant_monthly_income.feature
- features/mtr/dependant_allowance.feature
- features/partner/partner_assessment.feature
- features/step_definitions/api_request.rb
- spec/factories/dependant_factory.rb
- spec/services/calculators/dependant_allowance_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-234
Changes to dependant allowances for MTR
---
> LEP-234 Dependant allowances with an new under 14 category

- config/thresholds/mtr-2026.yml
- features/mtr/immigration_and_asylum.feature
- spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-232
Change disposable_income thresholds
---
> LEP-232 Increase disposable income thresholds

- app/lib/swagger_docs.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-257
Add MTR documentation around main home in domestic abuse cases
---
> LEP-257 add documentation for main home in DA cases

- app/lib/swagger_docs.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-241
Update API description for the following attributes
- state_benefits.name
- cash_transactions.income.category
- regular_transaction.category
---
> LEP-241 Update swagger description for "benefits"

- spec/services/calculators/pension_contribution_calculator_spec.rb
No ticket
Add calls_bank_holiday tag to pension calculator test 
---
> add tag to pension calculator unit test

- app/services/calculators/income_contribution_calculator.rb
- config/thresholds/mtr-2026.yml
- features/mtr/income_contributions.feature
- features/step_definitions/api_request.rb
- spec/services/calculators/income_contribution_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-255
MTR income contribution bands
---
> LEP-255 MTR income contributions

- app/models/outgoings/housing_cost.rb
- app/services/calculators/housing_costs_calculator.rb
- app/services/collators/housing_costs_collator.rb
- spec/factories/cash_transaction_category_factory.rb
- spec/services/calculators/housing_costs_calculator_spec.rb
No ticket
Refactor of housing cost calculator spec to make it easier to work with. Specifically removal of arbitrary cash transactions  which cause issues during checking as they have to be accounted for in expectations
---
> Refactor of housing cost calculator test

- app/lib/capital/base.rb
- app/lib/capital/subtotals.rb
- app/lib/disposable_income/base.rb
- app/lib/disposable_income/subtotals.rb
- app/lib/disposable_income/unassessed.rb
- app/lib/employment_income_subtotals.rb
- app/lib/gross_income_category_subtotals.rb
- app/lib/person_disposable_income_subtotals.rb
- app/lib/person_gross_income_subtotals.rb
- app/services/calculators/income_contribution_calculator.rb
- app/services/collators/gross_income_collator.rb
- app/services/workflows/non_passported_workflow.rb
- config/thresholds/2018-04-08.yml
- config/thresholds/2019-04-08.yml
- config/thresholds/2020-04-06.yml
- config/thresholds/2021-01-28.yml
- config/thresholds/2021-04-12.yml
- config/thresholds/2022-04-11.yml
- config/thresholds/2023-04-10.yml
- config/thresholds/mtr-2026.yml
- features/mtr/gross_income.feature
- features/mtr/income_contributions.feature
- features/mtr/pensioner_disregard.feature
- spec/lib/disposable_income/subtotals_spec.rb
- spec/services/calculators/income_contribution_calculator_spec.rb
- spec/services/collators/gross_income_collator_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-256
Created minimum income contribution of £20
---
> LEP-256 MTR contribution minimum

- spec/fixtures/partner_financials.json
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-391
---
> LEP-391 fix up example JSON file from swagger doc

- app/lib/swagger_docs.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-249
---
> LEP-249 Add note about inaccessible capital

- app/lib/swagger_docs.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-392
Extend rswag tests so that they generate definitions for  partner sections in response
---
> LEP-392 add missing partner sections into Swagger docs

- features/mtr/dependant_allowance.feature
https://dsdmoj.atlassian.net/browse/LEP-235
---
> LEP-235 add notes to clarify scenarios under test in cucumber

- features/mtr/equivilization.feature
https://dsdmoj.atlassian.net/browse/LEP-233
---
> LEP-233 improve cucumber test for visibility

- features/mtr/pensioner_disregard.feature
https://dsdmoj.atlassian.net/browse/LEP-247
---
> LEP-247 added cucumber test for extra pensioner disregards

- features/mtr/immigration_and_asylum.feature
https://dsdmoj.atlassian.net/browse/LEP-194
---
> LEP-194 - Cucumber tests for Immigration and Asylum MTR thresholds

- app/controllers/v6/assessments_controller.rb
- app/lib/employment_income_subtotals.rb
- app/lib/swagger_docs.rb
- app/models/employment_or_self_employment_income.rb
- app/models/employment_payment.rb
- app/services/calculators/employment_monthly_value_calculator.rb
- app/services/calculators/multiple_employments_calculator.rb
- app/services/calculators/tax_ni_refund_calculator.rb
- app/services/decorators/v6/disposable_income_result_decorator.rb
- app/services/decorators/v6/gross_income_decorator.rb
- app/services/utilities/employment_income_monthly_equivalent_calculator.rb
- app/services/workflows/non_passported_workflow.rb
- features/mtr/employment.feature
- features/mtr/self_employment.feature
- lib/integration_helpers/test_case/employment_collection.rb
- lib/integration_helpers/test_case/v5/result_comparer.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/calculators/employment_monthly_value_calculator_spec.rb
- spec/services/calculators/multiple_employments_calculator_spec.rb
- spec/services/collators/gross_income_collator_spec.rb
- spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
- spec/services/decorators/v6/gross_income_decorator_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-259
---
> LEP-259 - Allow employment attribute "prisoner_levy"

- app/controllers/v6/assessments_controller.rb
- app/lib/employment_income_subtotals.rb
- app/lib/swagger_docs.rb
- app/models/employment_or_self_employment_income.rb
- app/models/employment_payment.rb
- app/services/calculators/employment_monthly_value_calculator.rb
- app/services/calculators/multiple_employments_calculator.rb
- app/services/calculators/tax_ni_refund_calculator.rb
- app/services/decorators/v6/disposable_income_result_decorator.rb
- app/services/decorators/v6/gross_income_decorator.rb
- app/services/utilities/employment_income_monthly_equivalent_calculator.rb
- app/services/workflows/non_passported_workflow.rb
- features/mtr/employment.feature
- features/mtr/self_employment.feature
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/calculators/employment_monthly_value_calculator_spec.rb
- spec/services/calculators/multiple_employments_calculator_spec.rb
- spec/services/collators/gross_income_collator_spec.rb
- spec/services/decorators/v6/disposable_income_result_decorator_spec.rb
- spec/services/decorators/v6/gross_income_decorator_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-388
Add "student_debt_repayment" attribute for 
- employment_details
- employment_income
- self_employment_details
---
> LEP-388 Deduct student debt repayments directly from salary

- features/mtr/student_debt_repayment/employment.feature
- features/mtr/student_debt_repayment/self_employment.feature
https://dsdmoj.atlassian.net/browse/LEP-388
Create separate cucumber tests for "student debt repayment"
---
> LEP-388 Update cucumber tests

- app/controllers/v6/assessments_controller.rb
- app/lib/swagger_docs.rb
- app/models/assessment.rb
- app/services/creators/assessment_creator.rb
- app/services/creators/full_assessment_creator.rb
- app/services/decorators/v6/assessment_decorator.rb
- db/migrate/20231011112013_remove_column_version_from_assessments.rb
- db/migrate/20231011144523_remove_column_level_of_help_from_assessments.rb
- db/schema.rb
- spec/factories/assessment_factory.rb
- spec/models/assessment_spec.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- spec/services/creators/assessment_creator_spec.rb
- spec/services/decorators/v6/assessment_decorator_spec.rb
- spec/services/workflows/main_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-264
---
> LEP-264 remove assessments.version and assessments.level_of_help from DB

- features/mtr/immigration_and_asylum.feature
- features/step_definitions/api_request.rb
- features/step_definitions/immigration_and_asylum.rb
https://dsdmoj.atlassian.net/browse/LEP-195
---
> LEP-195 Update step definitions for Immigration and Asylum Cases

- app/services/calculators/lone_parent_allowance_calculator.rb
- config/thresholds/mtr-2026.yml
- features/mtr/dependant_allowance.feature
- spec/services/calculators/lone_parent_allowance_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-395
---
> LEP-395 convert lone parent allowance to be 70% of adult allowance

- app/controllers/v6/assessments_controller.rb
- app/services/creators/remarks_creator.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/workflows/main_workflow_spec.rb
> LEP-345 refactor workflows

- config/thresholds/mtr-2026.yml
- features/mtr/income_contributions.feature
- spec/services/calculators/income_contribution_calculator_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-398
Contribution 'band z' turned out to be a myth. So remove 
---
> LEP-398 remove fictional band z from income calculation bands

- features/mtr/housing_benefit_disposable.feature
- features/mtr/housing_benefit_gross.feature
- features/step_definitions/api_request.rb
https://dsdmoj.atlassian.net/browse/LEP-243
Improve tests after BA feedback 
---
> Lep 243 mtr tests

- spec/services/summarizers/main_summarizer_spec.rb
No Ticket
Change a test to use match_array rather than equality as test wasn't order deterministic
> fix up flakey test by using match_array

- app/constants/cfe_constants.rb
- app/lib/person_disposable_income_subtotals.rb
- app/lib/swagger_docs.rb
- app/models/outgoings/council_tax.rb
- app/models/regular_transaction.rb
- app/services/calculators/council_tax_calculator.rb
- app/services/collators/outgoings_collator.rb
- app/services/decorators/v6/disposable_income_decorator.rb
- config/thresholds/mtr-2026.yml
- features/mtr/council_tax.feature
- spec/factories/outgoing_factory.rb
- spec/factories/regular_transaction_factory.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/calculators/council_tax_calculator_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-258
---
> LEP-258 Deduct Council Tax

- app/lib/calculation_output.rb
- app/services/concerns/assessment_eligibility.rb
- app/services/summarizers/assessment_proceeding_type_summarizer.rb
- app/services/summarizers/main_summarizer.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- app/services/workflows/passported_workflow.rb
- config/thresholds/mtr-2026.yml
- features/mtr/asylum_support.feature
- features/step_definitions/immigration_and_asylum.rb
- spec/services/summarizers/assessment_proceeding_type_summarizer_spec.rb
- spec/services/summarizers/main_summarizer_spec.rb
- spec/services/workflows/main_workflow_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-397
---
> LEP-397 remove proceeding types check

- app/models/assessment_error.rb
No ticket
Remove redundant model from codebase
---
> remove unused model

- app/controllers/v6/assessments_controller.rb
As the assessment controller acquires more code, it seems appropriate to DRY it up so that it doesn't get out of hand
---
> DRY controller

- app/controllers/v6/assessments_controller.rb
- app/lib/calculation_output.rb
- app/lib/eligibility_results.rb
- app/models/assessment_error.rb
- app/services/creators/gross_income_eligibility_creator.rb
- app/services/decorators/v6/assessment_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- app/services/workflows/non_passported_workflow.rb
- spec/services/decorators/v6/assessment_decorator_spec.rb
- spec/services/workflows/non_passported_workflow_spec.rb
This creates an 'eligibility result' object seperate from calculation result. It will allow the pipeline to be run more than once when required in the next PR.
---
> Lep 345 eligibility result

- app/constants/cfe_constants.rb
- app/lib/person_disposable_income_subtotals.rb
- app/lib/swagger_docs.rb
- app/models/cash_transaction.rb
- app/models/gross_income_summary.rb
- app/models/outgoings/priority_debt_repayment.rb
- app/models/regular_transaction.rb
- app/services/calculators/housing_costs_calculator.rb
- app/services/calculators/priority_debt_repayment_calculator.rb
- app/services/collators/disposable_income_collator.rb
- app/services/collators/gross_income_collator.rb
- app/services/collators/outgoings_collator.rb
- app/services/decorators/v6/disposable_income_decorator.rb
- app/services/remark_generators/orchestrator.rb
- app/services/remark_generators/payment_checker.rb
- app/services/remarks.rb
- app/services/workflows/main_workflow.rb
- config/thresholds/mtr-2026.yml
- features/mtr/priority_debt_repayment.feature
- spec/factories/outgoing_factory.rb
- spec/factories/regular_transaction_factory.rb
- spec/models/cash_transaction_spec.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/calculators/priority_debt_repayment_calculator_spec.rb
- spec/services/remark_generators/orchestrator_spec.rb
- spec/services/remark_generators/payment_checker_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-240
---
> LEP-240 Add 'priority_debt_repayment' category for outgoings, cash transactions and regular transactions

- app/services/creators/capital_eligibility_creator.rb
- app/services/creators/disposable_income_eligibility_creator.rb
- app/services/creators/gross_income_eligibility_creator.rb
- spec/spec_helper.rb
Tidy up eligibility creators making them easier to read and reason about in terms of thresholds
---
> LEP-345 tidy up eligibility creators

- README.md
> Fix type in readme

- spec/fixtures/partner_financials.json
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
We lacked this example.
The functionality relating to this example was added in [LEP-84](https://dsdmoj.atlassian.net/browse/LEP-84)
---
[LEP-84]: https://dsdmoj.atlassian.net/browse/LEP-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add schema example for partner/other_incomes

- app/lib/assessment_stats.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-401
RequestLog JSON payload filtering(without postgres JSON queries) to generate assessment stats. (https://docs.google.com/spreadsheets/d/1YB_JDQJpq_ZqYRbJ-FH53orLgIcuyBplgrDRl8BgY8M/edit#gid=0)
---
> LEP-401 assessment stats

- app/models/dependant.rb
- app/services/calculators/dependant_allowance_calculator.rb
- app/services/calculators/lone_parent_allowance_calculator.rb
- app/services/creators/gross_income_eligibility_creator.rb
- features/employment/child_uplift.feature
https://dsdmoj.atlassian.net/browse/LEP-344
---
Don't count children who earn > dependant threshold in list of dependants when raising threshold 
> LEP-344 don't count earning child in >4 children test

- app/models/gross_income_summary.rb
- spec/models/cash_transaction_spec.rb
- spec/models/gross_income_summary_spec.rb
No ticket
- Fix cash transactions ordering. 
- Cash transactions ordered by date ASC by default
---
> fix cash transactions ordering

- app/services/calculators/housing_costs_calculator.rb
- app/services/calculators/state_benefits_calculator.rb
- features/mtr/housing_benefit_disposable.feature
- features/mtr/housing_benefit_gross.feature
- features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/LEP-243
Slight improvement to readability of housing benefit tests.
---
> LEP-243 housing benefit test clarification

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-409
---
> LEP-409 remove code climate, restore undercover

- spec/requests/v6/assessments_controller/errors_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-331
Add invalid transaction test to prevent regressions in LEP-331 implmentation
---
> Added test for invalid cash transactions

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- app/services/govuk_bank_holiday_retriever.rb
No ticket
Remove nesty gem and small tidy ups
---
> Remove nesty gem and tidy up

- app/services/creators/cash_transactions_creator.rb
- spec/requests/v6/assessments_controller/errors_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-331
Refactor cash transactions validation to be more idiomatic, as a per-cursor to LEP-331
---
> Lep 331 cash txn invalid date test

- Changelog.md
Worth mentioning this in the changelog
https://dsdmoj.atlassian.net/browse/LEP-349
---
> LEP-349 Update Changelog.md

- .circleci/config.yml
- Changelog.md
- app/lib/gross_income/unassessed.rb
- app/services/creators/capital_eligibility_creator.rb
- app/services/creators/disposable_income_eligibility_creator.rb
- app/services/utilities/result_summarizer.rb
- spec/factories/capital_summary_factory.rb
- spec/services/utilities/result_summarizer_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-421
---
> LEP-421 Rename "pending" result to "not_calculated"

- Gemfile
- Gemfile.lock
- config/initializers/rswag_ui.rb
- spec/swagger_helper.rb
No ticket
Remove deprecation warnings from rswag-specs upgrade
---
> Complete rswag 2.13 upgrade

- app/lib/swagger_docs.rb
- app/services/creators/capital_eligibility_creator.rb
- app/services/creators/full_assessment_creator.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- spec/requests/v6/assessments_controller/proceeding_type_spec.rb
- spec/services/creators/capital_eligibility_creator_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-420
---
> LEP-420 make receives_qualifying_benefit and proceeding_types non mandatory

- Changelog.md
- app/lib/swagger_docs.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-412
---
> LEP-412 deprecate involvement_type

- app/lib/swagger_docs.rb
- app/services/decorators/v6/proceeding_types_result_decorator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- spec/requests/swagger_docs/v6/full_assessment_spec.rb
- spec/requests/swagger_docs/v7/full_assessment_spec.rb
- spec/requests/v6/assessments_controller/asylum_support_spec.rb
- spec/requests/v7/assessments_controller/errors_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-446
Restore client involvement type to v7 of the API
---
> LEP-446 restore v7 client involvement type

- config/thresholds/2018-04-08.yml
- config/thresholds/2019-04-08.yml
- config/thresholds/2020-04-06.yml
- config/thresholds/2021-01-28.yml
- config/thresholds/2021-04-12.yml
- config/thresholds/2022-04-11.yml
- config/thresholds/2023-04-10.yml
- config/thresholds/mtr-2026.yml
- config/thresholds/test-jan.yml
- spec/services/calculators/pensioner_capital_disregard_calculator_spec.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-462
Sync pensioner capital disregard threshold with CLA 
---
> LEP-462 - Update pensioner capital disregard thresholds

- app/lib/eligibility_results.rb
- app/lib/gross_income/subtotals.rb
- app/lib/result_wrapper.rb
- app/lib/workflow_result.rb
- app/services/creators/gross_income_eligibility_creator.rb
- app/services/decorators/v6/result_summary_decorator.rb
- app/services/workflows/main_workflow.rb
- app/services/workflows/non_means_tested_workflow.rb
- app/services/workflows/non_passported_workflow.rb
- app/services/workflows/person_workflow.rb
- spec/requests/v6/assessments_controller/gross_income_lower_spec.rb
- spec/requests/v6/assessments_controller/incomplete_spec.rb
- spec/requests/v6/assessments_controller/simple_spec.rb
- spec/services/creators/gross_income_eligibility_creator_spec.rb
- spec/services/workflows/main_workflow_spec.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/LEP-456
https://dsdmoj.atlassian.net/browse/LEP-467
Add test and fix for issue with incomplete sections
---
> LEP-456/467 - bug fix for capital filled + missing gross and disposable

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-466
Rename deploy keys to run keys in circle config
---
> LEP-466 stop using deprecated circle deploy step

- app/controllers/v6/assessments_controller.rb
- app/lib/swagger_docs.rb
- spec/requests/v6/assessments_controller/non_means_tested_spec.rb
- spec/requests/v6/assessments_controller/proceeding_type_spec.rb
- swagger/v6/swagger.yaml
- swagger/v7/swagger.yaml
https://dsdmoj.atlassian.net/browse/LEP-479
---
> LEP-479 Throw error on missing proceeding types for certificated cases

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LEP-383
Fixup deployment dependencies for main branch - specifically don't build and deploy production unless tests pass
---
> LEP-383 fix main dependencies

- deploy/helm/templates/cronjob-maintenance-tasks.yaml
- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
- deploy/helm/values/uat.yaml
https://dsdmoj.atlassian.net/browse/LEP-489
After integrating with cla_backend, cfe civil is seeing much higher production workloads than before. In response, it makes sense to increase the resources available to cfe civil so that it can serve its clients more effectively 
---
> LEP-489 tidy up resource limits

- Gemfile
- Gemfile.lock
- config.ru
https://dsdmoj.atlassian.net/browse/LEP-493
Add Prometheus ruby client to application
---
> LEP-493 add prometheus client

- .circleci/config.yml
- deploy/helm/templates/_envs.tpl
- deploy/helm/values/staging-mtr.yaml
https://dsdmoj.atlassian.net/browse/LEP-496
Create new environment for MTR testing alongside staging
---
> Lep 496 staging mtr environment

- .circleci/config.yml
- app/services/redact_service.rb
- spec/services/redact_service_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-504
Fix date of birth redaction code for 29th February 
---
> LEP-504 Fix leap year DOB redaction code

- .circleci/config.yml
No ticket
---
While checking on LEP-499, found that deploys no longer worked due to an out-of-date AWS orb. 
> Upgrade aws ecr

- README.md
- config/thresholds/mtr-2026.yml
- config/thresholds/values.yml
https://dsdmoj.atlassian.net/browse/LEP-495
Conversation: https://mojdt.slack.com/archives/C040DEGBZQQ/p1709056952768649
---
> LEP-495 Docs improved for FUTURE_THRESHOLD_FILE and test_only

- app/services/workflows/non_passported_workflow.rb
- spec/requests/v6/assessments_controller/capital_eligibility_ineligible_gross_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-1428
Fix non-passported to check for capital ineligibility when gross ineligible 
---
> EL-1428 Fix bug - capital reported eligible when over threshold and gross ineligible

- deploy/helm/templates/ingress.yaml
- deploy/helm/templates/metabase-deployment.yaml
- deploy/helm/templates/metabase-service.yaml
- deploy/helm/values/production.yaml
- deploy/helm/values/staging-mtr.yaml
- deploy/helm/values/staging.yaml
- deploy/helm/values/uat.yaml
https://dsdmoj.atlassian.net/browse/LEP-501
added a new deployment/service/ingress for metabase
added new values to be able to turn it on and off for specific envs
---
> LEP 501 add metabase to staging

- deploy/helm/templates/ingress.yaml
- deploy/helm/templates/metabase-ingress.yaml
- deploy/helm/templates/metabase-service.yaml
- deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-501
renamed the service as this was causing the issue on deploymnent.
extracted the metabase ingress into its own file as per original requirements of the ticket
---
> LEP-501 deploy metabase stg

- deploy/helm/values/production.yaml
https://dsdmoj.atlassian.net/browse/LEP-509
enable metabase in production
---
> LEP-509 turn on metabase in production

- deploy/helm/values/production.yaml
https://dsdmoj.atlassian.net/browse/EL-1466
Switch off metabase from production as its blocking deployments
---
> Try switching of production metabase as its blocking deployments

- config/thresholds/2024-04-08.yml
- config/thresholds/values.yml
- spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/EL-1418
Uprating for child and partner allowance, starting on 8th April 2024
---
> EL-1418 upratings for cfe-civil 8th April 2024

- db/seeds/data/state_benefit_types.yml
https://dsdmoj.atlassian.net/browse/EL-1331
New Style JSA in benefits list
---
> EL-1331 Add new style JSA to Benefits list

- spec/services/collators/dependants_allowance_collator_spec.rb
https://dsdmoj.atlassian.net/browse/EL-1418
Fix failing test after 8th April 2024 happened
---
> EL-1418 rework - fixup test after 8th April 2024

- deploy/helm/values/production.yaml
https://dsdmoj.atlassian.net/browse/LEP-509
enabled metabase in production now that the jdbc_url is available in the evironment
> LEP-509 turn on metabase in production (again)

- .circleci/config.yml
No ticket
Upgrade CCQ environment to ruby 3.3.1 after CCQ upgraded
---
> Upgrade CCQ to ruby 3.3.1

- app/controllers/status_controller.rb
- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
- spec/requests/status_controller_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-XXX
---
> Disable metabase, fix health check

- deploy/helm/values/production.yaml
Turn in metabase to investigate outage
---
> turn on metabase temporarily

- deploy/helm/values/production.yaml
- deploy/helm/values/staging.yaml
https://dsdmoj.atlassian.net/browse/LEP-XXX
Testing on prod complete, this turns metabse prod back off and turns it on for staging so we can do more testing
---
> turn metbase off in prod and on for staging

- README.md
- config/application.rb
- deploy/helm/templates/_envs.tpl
- deploy/helm/values/production.yaml
- deploy/helm/values/staging-mtr.yaml
- deploy/helm/values/staging.yaml
- deploy/helm/values/uat.yaml
- spec/models/threshold_spec.rb
https://dsdmoj.atlassian.net/browse/LEP-465
Remove deprecated feature (as it was superceded by FUTURE_THRESHOLD_FILE) 
---
> Remove USE_TEST_THRESHOLD_DATA

- app/reports/assessment_stats.rb
- spec/spec_helper.rb
https://dsdmoj.atlassian.net/browse/EL-1649
Moved file and comments
---
> EL-1649 move comments and file location

- app/services/collators/outgoings_collator.rb
https://dsdmoj.atlassian.net/browse/EL-1651
Added common method for select statements
---
> EL-1651 refactor outgoings collator

- app/services/workflows/person_workflow.rb
https://dsdmoj.atlassian.net/browse/EL-1652
Reduce duplication within the person workflow to use private methods
---
> EL-1652 person wflow

- .github/workflows/gajira.yml
https://dsdmoj.atlassian.net/browse/EL-1834
- set-up gajira for CFE
---
> EL-1834: Set-up gajira for CFE

- features/BBB_CFE_Integration_Test_V3_Passported/P1-3-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P1-4-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P3-1-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P3-2-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P4-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P5-V5.feature
- features/BBB_CFE_Integration_Test_V3_Passported/P6-V5.feature
https://dsdmoj.atlassian.net/browse/EL-2100
Added cucumber features for passported spreadsheet tests BBB
---
> EL-2100 convert spreadsheet test to python

- features/EEE_CFE_Integration_Test_V3_Pensioner_Capital/NP_Pens1-V5.feature
- features/EEE_CFE_Integration_Test_V3_Pensioner_Capital/NP_Pens2-V5.feature
- features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/EL-2179
- If applied, this converts EEE spreadsheet tests into cucumber tests
- Also adding in 3 new step definitions, to help with frequency, date range & object initialisation 
---
> EL-2179: Convert passported (EEE) tests to cucumber

- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_1-v5.feature
- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_2-v5.feature
- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_4-v5.feature
- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_5-v5.feature
- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_6-v5.feature
- features/GGG_CFE_Integration_tests_EmploymentTests/GGG_EMP_7-v5.feature
- features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/EL-2182
---
> EL-2182 Google Sheet Employment Income tests G1-7

- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-1.feature
- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-2.feature
- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-3.feature
- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-4.feature
- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-5.feature
- features/HHH_CFE-IntTests-client-involvement-type/hhh-cit-6.feature
https://dsdmoj.atlassian.net/browse/LEP-XXX
---
> EL-2217: add first 6 tests for client involvement type

- spec/integration/test_runner_spec.rb
no ticket
fixes pipeline by removing google sheet tests
ticket to remove code to follow
---
> remove test runner

- docs/pull_request_template.md
https://dsdmoj.atlassian.net/browse/EL-2176
- If applied, this updates the gitHub PR template
---
> EL-2176: Update GitHub PR template

- features/CCC_CFE_Integration_Test_V3/NPE6-1-Cash-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE6-1-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE6-2-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-1-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-2-Cash-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-2-V5.feature
- features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/EL-2273
Convert 1st batch of CCC google sheet tests to cucumber
---
> El 2273 convert ccc tests to cucumber

- features/CCC_CFE_Integration_Test_V3/NPE10-2-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE10-3-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE10-5-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-3-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-4-V5.feature
- features/CCC_CFE_Integration_Test_V3/NPE9-6-V5.feature
- features/step_definitions/api_request_steps.rb
https://dsdmoj.atlassian.net/browse/EL-2274
Convert 2nd batch of CCC google sheet tests to cucumber
---
> El 2274 convert ccc tests to cucumber

- features/CCC_CFE_Integration_Test_V3/DependantNP1-V5.feature
- features/CCC_CFE_Integration_Test_V3/DependantNP2-V5.feature
- features/CCC_CFE_Integration_Test_V3/DependantNP2_Threshold-V5.feature
- features/CCC_CFE_Integration_Test_V3/DependantNP2_Threshold-V6-2023.feature
- features/CCC_CFE_Integration_Test_V3/pensioner-V6-2023.feature
https://dsdmoj.atlassian.net/browse/EL-2323
Convert 3rd batch of CCC google sheet tests to cucumber
---
> el-2323: Convert ccc tests to cucumber

- README.md
https://dsdmoj.atlassian.net/browse/EL-2415
- If applied, this adds some details about `port-forward-pod` in the readme
> EL-2415: Update readme.md with `port-forward-pod` info

- README.md
> Fix Google Drive link

- deploy/helm/templates/_envs.tpl
- deploy/helm/values/uat.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6235) move uat postgres user to aws secrets manager.
- Tests and rubocop should be passing: `bundle exec rake`.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) should be followed.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have …
> ap-6235: move uat postgres user to aws secrets manager
